### ISSUE TITLE
Infer result types

### ISSUE THREAD

**Issue by kvark** [gfx-rs/rspirv#103]
Being explicit about the result type in each instruction is redundant in most cases. There are exceptions, where the result type is a part of the semantics (to be added):
  - `OpCopyLogical`

I wonder if we could strip it away from SR, and just take special care of the exceptional instructions, by adding a more information in the instruction itself (e.g. a field in the instruction enum variant) about what it does.

The expected benefit from this would be less work for transforming and validating SR.

**Comment by Skepfyr** [comment]
Won't the result type decorations affect the semantics?

**Comment by kvark** [comment]
@Skepfyr yes, in a few cases. Currently `OpCopyLogical` is the only known (to me) case.
For these cases we could extend the Op to have some information about the return type, leaving the majority of Ops to be inferring their result types.

**Comment by Skepfyr** [comment]
True, although what's the benefit, we would have to work through every operation, work out whether any decoration could possibly affect any semantics. And then, we would have to include it for the extended instruction sets anyway as we don't know what the instructions even are ahead of time.

**Comment by kvark** [comment]
> The expected benefit from this would be less work for transforming and validating SR.

Obviously, this would only work if there is only a very few of those that we'd need to treat separately.

**Comment by Skepfyr** [comment]
What do you mean by less work? The code would have to exist for the ones that it does semantically matter and performance really shouldn't be a concern (I'll happily be proven wrong on that front but only with some hard data).

**Comment by Skepfyr** [comment]
In any case, I'm not sure we can assume as much as you are suggesting about the semantics that consumers care about.

**Comment by antiagainst** [comment]
`OpCopyLogical` is just one of the examples. Others include the cast instructions like `OpBitcast`, `OpUConvert`, `OpSConvert`, `OpFConvert`, etc. There are quite a few ops; see the list in "3.32.11 Conversion Instructions".

I'm not a fan of having special cases in the core infrasturure for instructions, unless there is really a compelling reason. I think we should have a common infrasture that works for all the instructions.

What's the motiviations behind removing the result type from instructions? By doing that, isn't we removing all type annotations from the infrastructure? (Because right now we don't have a dedicated SSA `Value` class, which has an associated `Type`, in rspirv like other compilers. So `Value` are essentially merged into `Instruction` here given one instruction in SPIR-V can generate at most one result SSA value.) It means, to perform any analysis or transformations on a block, we need to go back the *whole* use-def chain to trace back to the original constant/variable/parameter? For example,

```spirv
%0 = OpLabel
%1 = OpAccessChain %var ...
%2 = OpAcessChain %1, ...
%3 = OpAccessChain %2, ...
...
%100 = OpLoad %99
```
How do I know `%100`'s type given that none of the previous `%3`,`%2`, etc. have result types? We need to go back to `%1` to get its type, right? And this should happen whenever we need to query the result types; each query now becomes a recursion. It's much more computation during runtime. I'm not sure this qualifies as less work for transforming.

Removing types also means it's much easier to generate invalid IR. Because we have the result type associated with an instruction, we can verify *locally* whether an instruction is valid or not (and an instruction's verification only need to concern itself for the most of the cases). When we try to replace an instruction with another one, it's easy to catch the invalid case if the new instruction does not have a consistent type with the existing one. Without types, we must resolve to (potentially) full module verification to guarantee the basic correctness. These instruction replacement can happen very frequently (compiler transformations are just doing this anyway) so huge cost. Or if we don't verify after each pass, then we will have fun debugging faulty compiler passes. :)

**Comment by kvark** [comment]
> There are quite a few ops; see the list

Isn't that great? We could assign a class "Conversion" to them, which would clearly isolate the desired semantics.

> I'm not a fan of having special cases in the core infrastructure for instructions, unless there is really a compelling reason. I think we should have a common infrastructure that works for all the instructions.

Haven't we been doing this in one way or another? We were splitting all the instructions into different sets based on the semantics, so that we can have a richer expression of these instructions by the type system.

> What's the motivations behind removing the result type from instructions?

In most cases, result type is *redundant*. This means that whenever we touch it, we have to ensure that it's consistent with the rest of the state. Redundancy involves writing more testing and validation code.

Worth noting that even for conversion ops the result type is very constrained: a typical convert operation can only vary the result type by its width. I don't yet know how this will roll out, but there is an opportunity here to encode these constraints into the type system. I.e. the `OpConvertFToU` could look this way:
```rust
enum Op {
	...
	ConvertFToU {
		result_width: IntWidth,
	}
}
```

> By doing that, isn't we removing all type annotations from the infrastructure?

Sounds about right. Is there anything wrong with this?

> It means, to perform any analysis or transformations on a block, we need to go back the whole use-def chain to trace back to the original constant/variable/parameter?

The association of `Token<Op> -> Token<Type>` can be produced by a single linear pass over `Storage<Op>`, assuming that operations are added in such an order that all the dependencies are already in the storage. It would basically produce a `Vec<Token<Type>>`, addressable by `Token<Op>` in some way. Also, when lifting from DR we get that association right away.

This is a bit hand-wavy, since there technically is a choice of whether the types of operations should even be in any `Storage<Type>` as opposed to something like:
```rust
enum OpType {
	Token(Token<Type>),
	Implicit(Type),
	Void,
}
```

> And this should happen whenever we need to query the result types; each query now becomes a recursion. It's much more computation during runtime. I'm not sure this qualifies as less work for transforming.

I do agree that having the recursion for a query would be completely unacceptable. To re-iterate the previous note, the assumption is that it's cheap to infer *all types* at once for a module, in case a transformation pass needs them.

> Removing types also means it's much easier to generate invalid IR. Because we have the result type associated with an instruction, we can verify locally whether an instruction is valid or not (and an instruction's verification only need to concern itself for the most of the cases).

This isn't necessarily any different with this proposal. If we have the type association known, when replacing one instruction we can in O(1) check if the result type is different. If it's not - there is nothing to do. If it is different, we either need to re-validate the children instructions (ones that depend on the result of the replaced one), or to try re-computing their result type. Either way - it seems like it would be the same amount of work.

Overall, there appears to be a fair share of isomorphism between validation and derivation in this choice. Say, when multiple instructions need to be replaced, we can re-infer the result types in a single pass after the fact, if needed, just like we'd want to re-validate the module, if any of the return types are changed. If no return types are changed - in either approach there is no work that needs to be done.

Am I missing some important detail here? I don't feel strongly about this position, but I think it's worth arguing over.
