### ISSUE TITLE
Publish 1.3.5 of spirv-headers

### ISSUE THREAD

**Issue by Jasper-Bekkers** [gfx-rs/rspirv#108]
Now that #97 and #100 landed I would love to be able to depend on spiv-headers proper again. Would you mind publishing a new version?

**Comment by kvark** [comment]
I don't have a problem with that. Changes seem backwards compatible. @antiagainst anything to check before we proceed?

**Comment by antiagainst** [comment]
SGTM! Please feel free to proceed. The version number is tracking the spec version.  So the next one would be 1.4.1. One thing to keep in mind is that we use a custom verison of [core grammar](https://github.com/gfx-rs/rspirv/blob/master/autogen/external/spirv.core.grammar.json) (with categories added and adjusted a bunch of names there) so bumping the version will require manually merge upstream changes with our version. (I'm sorry about this. The changes should really be upstreamed, at least those components that make sense.) I'd recommend going into 1.4.1 instead of 1.5.1 (which is the current spec version) so that we can minimize the changes needed to merge and also a consumer can specifically pin to this version if needed. The procedure would be: diff the current in-tree grammar with the current tracked upstream grammar, update the git submodule for spirv-headers to https://github.com/KhronosGroup/SPIRV-Headers/commit/c4f8f65792d4bf2657ca751904c511bbcf2ac77b and then apply the changes to get a newer version of the custom grammar.

**Comment by Jasper-Bekkers** [comment]
Wouldn't it make sense to publish both 1.4.1 and 1.5.1 so we're up to date with the latest spec version as well?

**Comment by antiagainst** [comment]
Certainly. My previous point was that let's not omit 1.4.1 and jump to 1.5.1 directly. :) We should update to 1.5.1 to catch up with the spec for sure. :)

**Comment by Jasper-Bekkers** [comment]
I've submitted 2 PRs #115 and #116 that update the json files.

**Comment by azriel91** [comment]
Heya, please may I bump this :wave:. The current `spirv_headers` version on crates.io depends on `num-derive 0.1.44` which brings in `syn 0.12.15`. I'm slowly chewing through updating the Rust ecosystem :smile:

**Comment by kvark** [comment]
@azriel91 so you are blocked on #116?

**Comment by azriel91** [comment]
Heya, yeaps.

**Comment by antiagainst** [comment]
The `syn` dependency is due to `derive_more` used by `rspirv`. If one bumps the version of `derive_more` to `0.99` then `syn` will go away. But that results in some compilation failures I haven't gotten time to look into it.

**Comment by azriel91** [comment]
ah, I can do that -- am comfortable with `syn`.

**Comment by Jasper-Bekkers** [comment]
Closing because 1.5 got merged to master now.
