### ISSUE TITLE
Instruction: Derive Eq and Hash

### ISSUE THREAD

**Issue by nicokoch** [gfx-rs/rspirv#16]
hey, for a personal project I need to store Instructions in a HashMap.

Can these derives be added to Instruction?

**Comment by antiagainst** [comment]
That sounds good to me. :)

**Comment by antiagainst** [comment]
Hi @nicokoch,

I just checked it again. It is not very easy to

**Comment by antiagainst** [comment]
Sorry, accidentally clicked on the "close and comment" button with a premature post (deleted).

I just checked again. It is not possible to `#derive[Eq]` for `mr::Operand`, which is used in `mr::Instruction`, because `mr::Operand` can contain a `f32` or `f64` value. `f32` and `f64` do not implement `Eq` or `Hash`.

We can implement `Eq` for `mr::Operand` manually, but is it necessary to use the whole instruction as the hash key? Calculating the hash of a `mr::Instruction` using all its parts is not cheap I think. Does partial information, like the result id, of the instruction works? For the instructions without result ids it may be a problem. But other parts can be used maybe?

**Comment by nicokoch** [comment]
I'm not entirely sure. Partial information should work, but it should be as unique as possible.
