### ISSUE TITLE
LLVM-IR/MIR to SPIR-V? 

### ISSUE THREAD

**Issue by jon-chuang** [gfx-rs/rspirv#164]
Such tools exist [in C](https://github.com/KhronosGroup/SPIRV-LLVM-Translator) and the opposite direction was listed as a possibility. 

So how likely is this direction?

**Comment by antiagainst** [comment]
Hi thanks for the interest! Please note that SPIR-V is just a common intermediate langauge used by many APIs like Vulkan/OpenGL/OpenCL. So it typically depends on which flavor of SPIR-V you are talking about when thinking about this kind of conversions because it involves semantics. Also what's the scope of the incoming LLVM IR/MLIR. But anyway, converting LLVM IR to SPIR-V is a non-trivial task that involves many challenges. It is out of the scope of this project at the moment.
