### ISSUE TITLE
spirv: Vulkan SDK based versioning

### ISSUE THREAD

**Issue by msiglreith** [gfx-rs/rspirv#225]
The current SPIR-V version used is 1.5.4 which is almost 1 year old. With the latest Vulkan SDK, SPIR-V headers are tagged with the SDK version, which should update more regularly. This couples it more with the Vulkan version scheme tho.

Latest: https://github.com/KhronosGroup/SPIRV-Headers/releases/tag/sdk-1.2.198.0

**Comment by MarijnS95** [comment]
@msiglreith Thanks! Blame https://github.com/KhronosGroup/SPIRV-Headers/issues/199 for not being pinged about this release! I have sneakily been keeping this up to date in https://github.com/gfx-rs/rspirv/pull/226 - still needs one clippy/check fix, but it's already usable.

**Comment by MarijnS95** [comment]
> This couples it more with the Vulkan version scheme tho.

As for basing our version on the SDK, we've intentionally not done that when restarting with the `spirv` crate because of https://github.com/gfx-rs/rspirv/issues/196 - we cannot restart counting all over again for the `rspirv` crate either. The main problem here is that our API (what we generate and write by hand) may change regardless of what changed in the SDK release. Hence we use "version metadata" to indicate what version it is generated against.

(Unless you were merely _mentioning_ that SPIR-V is now following SDK versioning, and are _solely requesting rspirv to update_)

**Comment by msiglreith** [comment]
The last part was mostly related to tying it closer to Vulkan as main consumer/driving force for SPIR-V modules, in case this is not desired. As the current version scheme is more general purpose (ie OpenCL).
For me the `sdk-1.2.198` is fine - happy to have access to some newer SPIR-V operands :)

**Comment by MarijnS95** [comment]
I personally don't really mind, just happy SPIRV-Headers finally starts tagging their commits after a massive period of silence.

For (r)spirv we'll just keep following the semver we got going already, with the `+sdk-1.2.182` version metadata appended :)

**Comment by MarijnS95** [comment]
@msiglreith This issue is resolved now that we moved from [`spirv_headers`](https://crates.io/crates/spirv_headers) to [`spirv`](https://crates.io/crates/spirv), right? We have our own versioning scheme now so that breaking changes on the Rust side are properly separated from the SPIR-V headers (we'll have to do a breaking bump when they do a breaking bump though), and the version metadata "field" is used to relay the SPIR-V version a particular Rust `spirv` release was generated from.

Unfortunately the requested release of the first SDK regen in #226 hasn't made it into a release yet, but I'm not sure if this issue is just requesting a release anymore, or was only raising awareness about finally getting newer `SPIRV-Headers` tags.

**Comment by msiglreith** [comment]
Right thanks, this was more about keeping the source more in-sync with the SPIRV changes given the SPIRV release cycle were very long
