### ISSUE TITLE
Disassembling constant literals is broken

### ISSUE THREAD

**Issue by kvark** [gfx-rs/rspirv#227]
Looking at the disassembler logic, it prints out operands without any context. So for constant literals, it just prints them as a sequence of `u32`. This doesn't work for negative integers, and it likely breaks on 64-bit types.

See [shader playground](https://shader-playground.timjones.io/c6b6f3ae081a8a79b75e917520ca6649):
> %int_n2 = OpConstant %int -2

Downloading the binary and running it through `dis` in this repo gives me:
> %5 = OpConstant  %4  4294967294

Trying to assemble it back into SPIR-V using `spirv-as` fails with:
> error: 29: 23: Integer 4294967294 does not fit in a 32-bit signed integer

**Comment by supervacuus** [comment]
Hi, I had a brief look into this and wondered whether to fix it by adding signed/unsigned integer literals to the parser. Right now, the parser discards the sign of the tracked type when parsing literals:

https://github.com/gfx-rs/rspirv/blob/master/rspirv/binary/parser.rs#L312-L318

Generating signed integer literals at this point and correctly applying them throughout the code would fix this issue. The integer literals are already a specialization away from SPIRV's JSON grammar, so I don't think this change would break with spec. But introducing/changing literals might affect the parser's contracts to other code. If that direction sounds right, I can create a PR with my changes.

**Comment by supervacuus** [comment]
I've added a PR which only touches the disassembler. Modifying the parser as proposed above will break client code, if it expects matches on `LiteralIntXX` to mean all (= signed + unsigned) integer literals in the binary.

If breaking client code is okay for the convenience of no longer needing to track `OpTypeInt`, then I can create a very drafty alternative PR. But reading through your other issues, it might make more sense to handle this in SR rather than DR.
