### ISSUE TITLE
Release `spirv:0.3.0+sdk-1.3.243.0` not on crates.io

### ISSUE THREAD

**Issue by exrook** [gfx-rs/rspirv#245]
It would be nice to have `0.3.0+sdk-1.3.243.0` available on crates.io.

Alternatively, merge my pr #244 that updates to `sdk-1.3.268.0`, then push a new crates.io release :)

**Comment by exrook** [comment]
This would require a semver version bump to `0.3.0` due to breaking changes since `0.2.0+1.5.4`

**Comment by MarijnS95** [comment]
Yeah, you won't be allowed to publish the same version (`0.2.0`) with different version **metadata** (which is not part of the version and only for informative purposes).

The metadata has been bumped when we pushed the last regeneration, but it never made it to a release **yet**.

**Comment by exrook** [comment]
@MarijnS95 Are there any blockers to getting a new release pushed? I think merging my pr #244 should handle all the code changes, on the other hand just publishing the current master as `0.3.0` would also serve my needs if there's not resources to review updating to a new SPIRV release. I'd be happy to submit another PR with just the version number increment if that can help get a release published sooner, or if there's anything else I can help with please let me know :)

**Comment by MarijnS95** [comment]
@exrook the main blocker is me not having any maintainer rights whatsoever. This not only makes me unable to help out with your request right now, it also makes it less enticing to contribute consistent improvements and updates as well as perform code reviews and maintenance.

**Comment by exrook** [comment]
@MarijnS95 Ah that's unfortunate, sorry for barking up the wrong tree. Thanks for looking at this anyways though :).

Do you know which of the maintainers would be most likely to help? I don't want to burden anyone who doesn't have time to work on this, but I would really appreciate seeing a new release to crates.io eventually. Alternatively, maybe we can get someone from the @gfx-rs org to step in if the current maintainers don't have bandwidth to work on this crate at the moment.

**Comment by MarijnS95** [comment]
Maybe @msiglreith is most active to help us out?

**Comment by msiglreith** [comment]
Unfortunately I don't have publishing rights for the crate either see https://crates.io/crates/rspirv 
Last publishes were done by @Jasper-Bekkers

**Comment by MarijnS95** [comment]
Maybe we could at least get some PRs reviewed and merged, then have some more folks with publishing rights or set up the key in CI for automation.

**Comment by antiagainst** [comment]
@MarijnS95 @msiglreith I've sent invites to you to the rspirv crate. I won't have bandwidth to handle in the forseeable future unfortunately; but would like to see if this continue to be supported in good hands. Let me know if there are any other blockers. Thanks again! :)

**Comment by Firestar99** [comment]
With the publishing rights problem seemingly resolved, could we get an update on crates.io? I would very much be interested in the symbols for mesh shaders. And thanks for your efforts to get it updated :D

**Comment by msiglreith** [comment]
Aiming to release a new version in the next days

**Comment by MarijnS95** [comment]
@Firestar99 we're working on already, see active PRs (#248).

**Comment by msiglreith** [comment]
Could someone add me to `spirv` crates.io as well? I just realized while creating a release that I have rights for `rspirv` but not the other one

**Comment by MarijnS95** [comment]
@msiglreith sent!

Do you have the rights on this repo to add secret tokens? Because I don't :sweat_smile:

**Comment by MarijnS95** [comment]
@msiglreith I've published the release for `spirv 0.3.0` by hand so that you don't have to fiddle with force-pushes to get the CI to respond again (and to reset the tags etc). I'll leave you to tackle `rspirv`.

Though in hindsight GitHub supports simply re-running a CI job, which might have solved this as well if your API key in GitHub secrets is allowed to publish to this crate.

**Comment by msiglreith** [comment]
@MarijnS95 Thanks! Yes, as I can add tokens as I'm organization owner heh - I increased your rights to `Maintainer` but not clear to me if this is sufficient. The token I added should work for both tho, but there seems no warning on crates.io when you add repositories you don't own.
![grafik](https://github.com/gfx-rs/rspirv/assets/7253845/5713eb54-fa19-4254-ae94-a53357e663c4)

I created and published a new `rspirv` version as well but seems the process needs a few more fixes. Added following points on my todo list:
- commit messages are not generated correctly, seems to be due to `consolidate-commits = true`
- publish CI fails too early due to `spirv` already being published

Anyway, new `spirv` and `rspirv` versions are available!

**Comment by MarijnS95** [comment]
Nope, only have access to a few basic settings. Thanks anyway!

The crates are said to be a "pattern", perhaps there's no check to see if it matches anything (in case you haven't published it yet... But also in case your pattern matches another crate that already exists but is not yours?)


> * commit messages are not generated correctly, seems to be due to `consolidate-commits = true`

Yes, this is a little terrible situation, but not sure how it is supposed to be fixed. Maybe only works with individual releases or with `minor` as argument?
