### ISSUE TITLE
Case against is_type() methods

### ISSUE THREAD

**Issue by kvark** [gfx-rs/rspirv#42]
There is a large auto-generated section looking like:
```rust
impl Type {
  pub fn is_foo(&self) -> bool {...}
  pub fn is_bar(&self) -> bool {...}
  ...
}
```
It enumerates each and every enum variant.

What is the motivation behind this API? I think we could live without it. The more complex (and semantically rich) checks would stay and just pattern match internally:
```rust
impl Type {
    pub fn is_numerical_type(&self) -> bool {
    }
    pub fn is_scalar_type(&self) -> bool {
    }
    pub fn is_aggregate_type(&self) -> bool {
    }
    pub fn is_composite_type(&self) -> bool {
    }
}
```

**Comment by antiagainst** [comment]
The rationale is that in compiler code base checking a type's value is quite prevalent. Just trying to throw out some line savings here by turning the 4-line `match` into one method call. It's small-ish per site, but it adds up. :)

Given this is already there; we can keep it. After coding more components out then we can re-evaluate the situation and delete it if it ends up not being used that much.

**Comment by kvark** [comment]
Continuing from https://github.com/gfx-rs/rspirv/pull/67#issuecomment-518730528

> Hiding internals of Type and make its new method not public is for that purpose.

I don't think this conflicts with the idea of having `Context` to de-duplicate the types. You can still do this:
```rust
let type = Type { ... }; // set it up manually
let token = context.add_type(type);
```

> probing its properties, which is intended to be achieved via those is_* method

But `is_*` method doesn't *give* you the properties, it just tells you if a type belongs to a particular kind. What if, say, I want to analyze SPIR-V types and map them to Metal types. I got `Type { ty: TypeEnum::Int { width, signedness }, decorations: Vec::new() }`. If all I can do is `is_int()` on that type, how do I figure out if it maps to `int`, `uint`, `short`, etc?

What is the downside of just exposing the type system instead of hiding it behind a bunch of `new_xx` and `is_xxx` methods?

**Comment by antiagainst** [comment]
I think we are conflating multiple things here:
1. Whether having `is_*_type` checks is useful (which is what this issue about)
1. Whether we want to make Type construction only available via `Context`
1. Whether we want to expose the internals of `Type`
1. Whether we want to merge `Context` into `Module`

Let's discuss one at each time instead of mixing them together. :)

For 1.

As I said in the [above](https://github.com/gfx-rs/rspirv/issues/42#issuecomment-513070241), the `is_*_type` method is a syntax sugar for the normal `match`: it replaces a normal `match` with a oneliner. Note that checking the type is a very common task in compilers so I believe it makes sense to have some syntax sugar around to save all those `match` expressions everywhere. Does this make sense?

For 2.

Quoting myself from https://github.com/gfx-rs/rspirv/pull/67#issuecomment-518730528

> All types should be uniqued into Context and created from Context. Hiding internals of Type and make its new method not public is for that purpose.

To further explain:

A `Type` is highly coupled with a `Context`. E.g., an array type references an element type via a `Token` that only makes sense to the `Context`. By forcing all type construction happening in `Context`, it is a strong indication that `Type` cannot exist without a `Context` and we should make sure the `Token` referenced are from the same `Context`. (We probably could enforce this by having a `Context` reference in the `Token` but then lifetime is hard to handle... Rust is really not very easy on this front.) Allowing to create `Type`s freely causes confusion and embraces subtle problems. For example for the above two lines you wrote, can I continue to use `type` in following up code or must I use `token`? Can I use it to insert into another `Context`? etc.  

For 3.

You are making a good point here regarding getting more detailed information regarding a type. We can add more getter methods like `get_int_bitwidth` but I guess that defies the purpose of syntax sugaring the use sites. Now we need to `is_int_type` and then `get_int_bitwidth`, which is not better than a simple `match` anymore. So I've no complains of making `Type` internals public. Just wanted to re-iterate that I do think the benefits of `is_*_type` holds. It does not mean we must not provide `is_*_type` methods if we open up `Type` internals; vice versa.

I think we may need to adjust names properly: changing `TypeEnum` to `Type` and changing `Type` to `DecoratedType` (or something). This better reflects their internals.

For 4.

In the compiler world having a `Context` for maintaining the lifetime of various constructs in the module is a well-known approach. It's a cleaner separation of concerns from layering's perspective. If we want to change it, apart from practices and layering, I think there are other implications to consider:

Merging  `Context` and `Module` means we won't be able to use the same `Context` for multiple modules, which means we won't be able to share lots of common types and constants among different `Module`s. It may or may not be a big problem depending on how many `Module`s we want to manipulate at the same time and how we want to make it parallel. I just feel at the current state I'm not able to tell for sure.

**Comment by kvark** [comment]
Thank you for the detailed response @antiagainst !

(1) I'm inclined to suggest that we re-add `is_type` checks if and when we'll need them. It's not obvious to me that we will. They may be common in C++ compiler world, but in Rust `match` is the answer.

(2) I don't think there is any confusion in being able to create a type without a context *as long as* you still have to register it (and obtain `Toke<Type>`) whenever you need to use or reference it.

(3) Suggestion to rename `Type` sounds good!

(4) Isn't this contradicting https://github.com/gfx-rs/rspirv/pull/71#discussion_r314170330 ? I'm confused now.

**Comment by antiagainst** [comment]
For 1

I don't think this is regarding what languages we choose unless Rust writes compilers differently than other languages, which I doubt is the case. :) The thing is, if we don't have these from the beginning, folks will just use `match` everywhere. I honestly don't see why writing four lines of code is better than one line? If it's not common I'm okay, but this is gonna be quite common... Rust `match` is super nice and those helper methods are mapping to use them under the hood. They are just syntax sugars. If we must use raw Rust APIs everywhere, it means we should not have most of the Rust crates out there? :) 

For 2

I think I don't see why having two separate calls, one creating a `Type` and another immediately registering it into a `Context`, is better than one `call` to create the `Type` out of a `Context` is better? Especially we cannot use the result of the first call except for registering it into a `Context`?

For 4

Sorry about the confusion! That was in the context of discussing whether those lift methods should belong to `Context`. DR uses result id numbers to "link" instructions. If lift methods are placed in the `Context`, we cannot import more than two DR modules because they can use different result id numbers for the same type and there will be no way to consolidate them. (AFAIK, the current implementation of `Storage` still keeps the original result id numbers.) So it naturally means we can only have one SR module. But generally for `Context` and SR module, we can go both ways: having one for each SR module or have one for multiple modules. It just has implications on memory footprint and multithreading behavior. As said before, it's unclear for me at the current moment which is definitively better. So if you have strong preference, I'm fine to go that way and revisit later. 

(Interestingly from layering's perspective, now module become a gigantic thing for all kinds of tasks: type/constant querying and uniquing, holding all functions/blocks/instructions, and having all those lifting methods. This makes me quite uneasy. Will the default become let's put everything in module and see how it goes?)

**Comment by kvark** [comment]
(1) I guess I'm just missing the use-cases in my head. Would you happen to have some that would indicate the usefulness of `is_type` from either the user or our (implementors) perspective?

(2) It's clearly superior to me: this model means that the API surface of the library becomes much thinner and yet more powerful: it only needs to expose the `Type` and some `Context::add_type()` method (as opposed to dozens of `is_type`, `new_type` methods and such). Users would be able to store `Type`, mutate it, send it over to other threads, debug print, serialize, etc, naturally. Users could still add a type with a one-liner, like
```rust
let type_token = context.add_type(Type::Vector { .. });
```

(4) After reading your comment and thinking about this some more, I think I see your point now. Please correct me if I got it wrong. So the model we'd want is something like this:
```rust
let mut context = Context::new();
let mut module1 = Module::new();
module1.types.push(context.new_type());
let dr1 = module1.to_data_representation(&context);
let module2 = context.lift_module(&other_dr_module);
```
In which case the `Context` would just accumulate all the things needed by modules that use it. When there is a need to convert to a DR, the `Token<>` references would still need to be converted to `<id>`, so it doesn't matter if the `Context` has stuff that isn't needed for a module - only the needed parts will be converted to `<id>` and end up in the DR.
Of course we'd want some better type or run-time protection against using a wrong `Context` for a module, but that's a technical issue we can postpone for now.

So, yes, I see that we *can* do it. But the question still stands - what would that give us?
is it just a way to avoid re-growing the storage vectors, or something else?

**Comment by AIOOB** [comment]
1.
I agree with removing `is_type` methods mostly because I can't actually see them being all that useful, especially if we let the Type enum components public `if let [Type] = ...` is much more idiomatic and just as short. In any case, using match is encouraged throughout rust as it encourages slightly better style, and I feel that users rarely need a boolean about what type something is, it would almost entirely be used for flow control. (I might be wrong about this)

2.
Again making `Type` internals public so users can destruct them inherently(I think?) makes them able to construct them. The only issue I see with the process is that aggregate types reference `Token<Type>`s which are bound to a `Context` and it makes no sense for them to be in a different one. I am not sure how to solve this, I'm going to have a think about it.

3.
I agree with renaming `Type` however I think we need to reconsider how we are dealing with decorations. As far as I can tell anything can be decorated in SPIR-V which makes storing the decorations intrusively a bit of a pain as we would need to scatter them everywhere, then again we probably only want decorations to be able to be applied to what they are speced to be able to be applied to.

4.
I agree that at some point we should probably move the lifting out of the Context/Module they are only used once in the conversion from dr to sr so shouldn't really hang around. It might even make sense to just stick them all in a `From<dr::Module> for sr::Module`. I feel that thinking about multithreading is not sensible for Module construction, you would have to be doing something really weird for it to actually be a bottleneck of an application, and it's also so interconnected that I'm not sure it would provide an advantage.

**Comment by antiagainst** [comment]
1.
@kvark:

For example, isn't this used frequently in instruction verifications? If I'm to verify that an `OpIAdd` has the current types for both operands, I think it would be easier to write something as `is_int_type() || is_int_vector_type()`. (This applies to all arithmetic instructions.) Another example, if we are verifying `OpSizeOf`'s pointer, I would think writing `is_scalar_type()` would be more readable and requires fewer lines than listing all the cases (bool, int, float) explicitly. This applies to all places that we want to check whether a component is a scalar. Similarly for composite. If I'm to check whether an operand of some field is a composite (e.g., for `OpCompositeExtract`), won't it be easier to write as `is_composite_type()` compared to `match` against all cases (vector, matrix, struct, array, runtime array)? Without these helper methods, one need to always make sure they list all of the cases at every place, not more and not less.

@AIOOB :

See the above for examples.

> In any case, using match is encouraged throughout rust as it encourages slightly better style

Acknowledged. I'm not saying we should avoid `match`. Both have their use cases. :) But if both of you hate it so much, please feel free to delete them given that you are working on it right now. :) 

2. 

@kvark:

>  the library becomes much thinner and yet more powerful: it only needs to expose the Type and some Context::add_type() method (as opposed to dozens of is_type, new_type methods and such).

Maybe this is just my personal understanding. But I'm not sure you are exposing a single API here. I consider `Type::Vector {...}` and `Type::Matrix {...}` as two APIs. I don't see a definitive difference here compared to `context.get_vector_type(...)` and `context.get_matrix_type(...)`. (The former might be more Rust idiomatic?) If you put it in one liner, you have `context.add_type(Type::Vector{...})`, which I fee is slightly verbose than `context.get_vector_type(...)`. 

> Users would be able to store Type, 

I think we want to operate on `Token<Type>` instead of `Type` directly? `Token` has a fixed size and a much smaller footprint. Why would you like to store the `Type`, which can be quite large (e.g., structs with lots of fields)?

> mutate it,

It's common to derive types based on some existing type. But I'm not so sure about mutating type.

> send it over to other threads,

This is what I mean by type and context are tightly coupled. Say if this is a vector type that contains a `Token<Type>` for a scalar, can we easily send it over to anther thread? Does the `Token<Type>` make sense there?

> debug print, serialize, etc, naturally. 

I think we can still do this by indexing the `Context` with `Token<Type>` ?

3.

@AIOOB : Yes, decorations is a bit painful. They are semantic-affecting metadata. It's also a heavy burden on verification. I don't have better solutions immediately.

4.
@AIOOB:

> It might even make sense to just stick them all in a From<dr::Module> for sr::Module.

I like that!

> I feel that thinking about multithreading is not sensible for Module construction, you would have to be doing something really weird for it to actually be a bottleneck of an application, and it's also so interconnected that I'm not sure it would provide an advantage.

Agreed. I was merely proposing the approaches that might be considered. Not strongly suggesting we should go that way.

@kvark:

Yes that's one of the reaons that I think we should keep the conversion logic (`lift_*` functions) out of SR module. It mixes in DR specific result `<id>`s.

>  I see that we can do it. But the question still stands - what would that give us?
is it just a way to avoid re-growing the storage vectors, or something else?

I think when design something it's better to think about different approaches and their implications. Sharing the `Context` can help to save memory usage. If we think that's not important compared to other factors, that's fine. Again, I'm not strongly advocating we go this way. I'm just pointing it out. Quoting myself:

> we can go both ways: having one for each SR module or have one for multiple modules. It just has implications on memory footprint and multithreading behavior. As said before, it's unclear for me at the current moment which is definitively better. So if you have strong preference, I'm fine to go that way and revisit later.

**Comment by antiagainst** [comment]
Okay, I feel I'm becoming a blocker for you folks to making progress. :) Given that you are implementing this right now, I'm fine to go with what you think are fine and we can always revisit later. :)

**Comment by kvark** [comment]
@antiagainst thank you for your feedback! On one hand, it's indeed hard to make quick progress (especially if both of me and @AIOOB are hacking around) when the review latency is high and the conceptual questions are not reaching consensus. On the other hand, if we start just landing whatever we have, we can easily end up with something that needs to be rewritten. Your advice is precious to us, please keep reviewing the PRs/issues within the time budget that you have.

1. This issue is specifically about the auto-generated `is_type` methods that only match a single variant. As I mentioned originally:
> The more complex (and semantically rich) checks would stay

We'll proceed with having a handful of them (like `is_scalar_type()`, `is_composite_type()`, etc) but removing all the auto-generated checks.

2. 
> If you put it in one liner, you have context.add_type(Type::Vector{...}), which I fee is slightly verbose than context.get_vector_type(...).

Indeed! The power of an API is to *allow* these specific `get_vector_type` constructs (designed to improve ergonomics, for example) to be build *on top* of a small number of powerful primitives, such as `Type` enum and a single `add_type()` method on the context/module.

I mostly agree with your argument that `Type` by itself may not end up being ultimately useful for the users. I feel that *letting* them have it is still a plus though.

4. I'm totally cool with `lift_()` functionality living outside of SR. But where?.. It feels like we can revisit this once we have it working :)
Similar reasoning applies to Context/Module: if it's not clear right now, let's pick the simplest path and re-evaluate later when we can see better.

**Comment by antiagainst** [comment]
>  please keep reviewing the PRs/issues within the time budget that you have.

Certainly. I'd love to review every PR and chime in every issue, but I just feel I don't have enough bandwidth to do that timely recently. Totally agreed that we should have some good discussion around architectural issues and feel free to ping me on those. But I guess most of the time it's not that critical as we cannot change the course easily (like 1 & 2 in the above). So I value progress much more on those aspects. :)
