### ISSUE TITLE
Duplicated code in Disassemble

### ISSUE THREAD

**Issue by nifker** [gfx-rs/rspirv#72]
From where is the code duplicated?
https://github.com/gfx-rs/rspirv/blob/master/rspirv/binary/disassemble.rs#L146-L170

**Comment by Skepfyr** [comment]
@antiagainst, I think you are the only one who can answer this. For reference, it is now here:
https://github.com/gfx-rs/rspirv/blob/master/rspirv/binary/disassemble.rs#L133-L153

**Comment by antiagainst** [comment]
Ah, sorry, It has been long enough that I myself lost track... The comment may already be outdated with recent developements. (Yeah, should really use some good comments there.) So please just ignore it.

**Comment by antiagainst** [comment]
Reading it a bit more, I remembered that I meant we have similar logic in `impl Disassemble for dr::BasicBlock` and `impl Disassemble for dr::Function`. Because of the `ExtInstSetTracker` thingie, I wasn't able to delegate the disassembling to `dr::Function`/`dr::BasicBlock`'s `dissassemble()` method directly. Clarified with https://github.com/gfx-rs/rspirv/commit/96bbb9f4925c8e23dde8c3cc83f2bda446c24219.
